= SBuild 0.6.0 released
:author: Tobias Reeser
:revdate: 2013-09-19
:summary: SBuild 0.6.0 was released with improvements in parallelization, downloading, error handling, scheme handler support and embedding.
:jbake-type: post
:jbake-status: published
:jbake-tags: Release

Another release which brings a lot of improvements and some minor API changes. 

Most notably, the `SchemeHandler` API was improved and together with the new `ResolveFiles` support, should allow feature rich scheme handler implementations (an Aether scheme handler is in the works).
Parallel execution of targets is now no longer experimental and can be activated and configured with the `--jobs` (`-j`) commandline option.
When used, SBuild will run targets, that don't depend on each other, in parallel.
If you need to express a dependency between two dependencies, you can use the new `~~` operator (instead of `~`) to denote a synchronization barrier.

The internal downloader was improved and now better handles failures and tries to resume and retry interrupted downloads.
It also sends a proper User Agent, which should fix some download problems some people experienced with Maven Central lately.
It also shows a meaningful progress for longer downloads.
In some other build setups you might welcome the new `--repeat` option, which will re-run the specified targets after a given time interval.
This version will also properly report build script and compile problems to the SBuild Embedder, which in turn will contribute to a better user experience of the  SBuild Eclipse Plugin.

Download the http://sbuild.tototec.de/sbuild/attachments/download/75/sbuild-0.6.0-dist.zip[SBuild 0.6.0 distribution] now.

Read the full link:SBuild_0_6_0#Changelog[Changelog].

I wish you fast and reliable builds.
And please provide any kind of feedback via our http://sbuild.tototec.de/sbuild/projects/sbuild/issues/new[issue tracker], the http://sbuild.tototec.de/sbuild/projects/sbuild/boards[forums] or as a mailto:tobias.roeser@tototec.de[personal email].

Best regards, +
Tobias
