= First steps on the Commandline
:author: Tobias Roeser
:revdate: 2013-12-13
:SBuildVersion: 0.7.1

SBuild's main interface is a command line tool called `sbuild`. 
It supports various options and will receive the targets, you want to build, as parameter. 
When invoked, it searches for a build file `SBuild.scala` in the current directory, reads it and executes the requested targets.

== Built-in Commandline Help

SBuild supports various commandline options. You can invokde `sbuild` with the `--help` or `-h` option, to get a list of all supported options and parameters with short descriptions.

.Output of `sbuild --help`
----
bash$ sbuild --help
SBuild 0.7.1 (c) 2011 - 2013, ToToTec GbR, Tobias Roeser

Usage: sbuild [options] [parameter]

Options:
  --additional-buildfile,-F FILE  Add an additional buildfile into scope.
  --buildfile,-f FILE             The buildfile to use (default: SBuild.scala).
  --check                         Check targets for cycles and missing scheme
                                  handlers.
  --check-recursive               Check targets of this project and all its
                                  modules for cycles and missing scheme
                                  handlers.
  --clean                         Remove all generated output and caches. This
                                  will force a new compile of the buildfile.
                                  (This will not remove output generated by
                                  buildfiles.)
  --create-stub                   Create a new minimal SBuild.scala file to
                                  start with.
  --define,-D KEY=VALUE           Define or override properties. If VALUE is
                                  omitted it defaults to "true".
  --dependency-tree               Show dependency tree(s) and exit.
  --execution-plan                Show the execution plan and exit.
  --fsc                           Use the fast scala compiler (client/server).
                                  The fsc compiler of the correct Scala version
                                  must be installed.
  --help,-h                       Show this help screen.
  --jobs,-j N                     Allow processing N targets in parallel. Use 1
                                  to disable parallel and 0 to use
                                  <number-of-cpu-cores> threads.
  --just-clean                    Remove all generated output and caches without
                                  reading any buildfile. This will essentially
                                  remove the ".sbuild" directory in the current
                                  directory.
  --just-clean-recursive          Remove all generated output and caches without
                                  reading any buildfile. This will essentially
                                  remove the ".sbuild" directory in the current
                                  directory and all sub-directories, no matter,
                                  if sub-directories contain SBuild projects or
                                  not.
  --keep-going,-k                 Keep going when some targets can't be made.
  --list-available-plugins        List all plugins available (used and unused)
                                  by this project.
  --list-modules                  Show a list of modules involved in this
                                  project.
  --list-plugins                  List all plugins used by this project.
  --list-targets,-l               Show a list of targets defined in the current
                                  buildfile.
  --list-targets-recursive,-L     Show a list of targets defined in the current
                                  buildfile and all modules.
  --no-color                      Disable colored output.
  --no-fsc                        Do not try to use the fast scala compiler
                                  (client/server)
  --no-global                     Do not read global settings from <USER
                                  HOME>/.sbuildrc.
  -q,--quiet,--no-progress        Quiet mode. Don't show progress messages with
                                  progress in percent. (This will speed up
                                  SBuild initialization.)
  --repeat SECONDS                Repeat the requested action after the given
                                  time (in seconds), but not before the previous
                                  run was completed.
  --verbose,-v                    Be verbose when running.
  --version                       Show SBuild version.

Parameter:
  TARGETS  The target(s) to execute (in order).
----

== The Buildfile

The buildfile contains all instructions and target descriptions and is typically written by the developer.

If `sbuild` does not found any buildfile, it will stop with an error message like this one:

----
bash $ sbuild 

SBuild detected an failure in the project configuration or the build scripts.
Details: Project file '/tmp/example/SBuild.scala' does not exists
----

The relevant error message tells you, that the buildfile `Sbuild.scala` is required to proceed but was not found in the current directory.

=== Using an alternative Buildfile

To use another buildfile, you can use the `--buildfile` or `-f` option.

.Using an alternative buildfile
----
bash$ sbuild -f MyBuild.scala
----

=== Creating a Buildfile stub

You you want to start a new SBuild project, you can use the `--create-stub` option, to let SBuild create a minial buildfile for you.

----
bash$ sbuild --create-stub

----

For an easy start you can instruct `sbuild` to create an minimal template file for you:

----
bash $ sbuild --create-stub
----

In case, you run `sbuild --create-stub` accidentally in a directory, where a buildfile already exists, SBuild will refuse to override it.

----
bash$ sbuild --create-stub 

SBuild failed with an unexpected exception (SBuildException).
Details: File SBuild.scala already exists.
----

=== The Stub Buildfile

Here is the content of a Buildfile created with `sbuild --create-stub`.

[source,scala]
----
import de.tototec.sbuild._

@version("0.7.1")
class SBuild(implicit _project: Project) {

  Target("phony:clean") exec {
    Path("target").deleteRecursive
  }

  Target("phony:hello") help "Greet me" exec {
    println("Hello you")
  }

}
----

This Buildfile contains the following information:

* It requires SBuild 0.7.1 or newer
* It contains two targets `clean` and `hello`
* Both targets are `phony`, which means, they do not produce a single file but constitute some tasks, and both contain some custom actions.

[NOTE]
--
You can customize the result of `sbuild --create-stub` by providing your own stub buildfile. 
To do this, you have to create a directory `stub` in the installation directory of SBuild (`${SBUILD_HOME}`) and place the template buildfile in that directory. 
If SBuild is run with the `--create-stub`, it will first search in that stub directory if it will find a file with the same name as the expected buildfile, namely `SBuild.scala`.

You can also provide more that one stub files with different names.
To select a specific stub file, e.g. `Setup.scala`, run SBuild with `sbuild --create-stub -f Setup.scala`.
Now SBuild will first search for a file named `Setup.scala` in the `${SBUILD_HOME}/sub` directory.
If one is found, this will be used as stub file, else the built-in default will be used.
Finally, you will find the newly created stub file in the current directory.
--

== Running SBuild

To execute one or more targets of a project, simple give the desired targets as parameters.

E.g. to execute the +clean+ and the +hello+ targets of the just created buildfile above, you will run `sbuild clean hello`. Following is the output of that command:

----
bash$ sbuild clean hello
Initializing project...
Compiling build script: /tmp/test/SBuild.scala...   <1>
[0%] Executing...
[0%] Executing target: clean   <2>
[50%] Finished target: clean after 4 msec
[50%] Executing target: hello
[50%] Greet me
Hello you
[100%] Finished target: hello after 0 msec
[100%] Execution finished. SBuild init time: 3,904 msec, Execution time: 57 msec   <3>
----

<1> If SBuild never run before or if it detects, that the buildfile has changed, it will compile the buildfile, thus the output `Compiling build script: ...`.

<2> After compilation of the buildfile, it will execute the required targets and print what it is actual doing paired with a handy progress report.

<3> At the end, you will see the `Execution finished` message and some little statistics.

In any subsequent run, compilation of the buildscript is not needed again and SBuild the execution of the requested targets start almost instantly.

----
bash$ sbuild clean hello
Initializing project...
[0%] Executing...
[0%] Executing target: clean
[50%] Finished target: clean after 2 msec
[50%] Executing target: hello
[50%] Greet me
Hello you
[100%] Finished target: hello after 0 msec
[100%] Execution finished. SBuild init time: 164 msec, Execution time: 55 msec
----


== Built-in project exploration

SBuild has some handy options, which let you easily explore a project. Most of these options also have a "recursive" variant, which includes also all modules (sub projects) into the output.

The most frequently used options are:

[cols="1,2"]
|====
| `--list-targets`, `-l`
| Show a list of targets defined in the current buildfile.

| `--list-targets-recursive`
| Show a list of targets defined in the current buildfile and all modules.

| `--list-modules`
| Show a list of modules involved in this project.

| `--list-plugins`
| List all plugins used by this project.

| `--list-available-plugins`
| List all plugins available (used and unused) by this project.
|====

== Project validation

// TODO

== Parallel execution

By default, SBuild will execute targets in parallel, to utilize the resources of modern multi-core hardware more efficiently.
You can customize the number of simultaneously used threads with the `--jobs` or `-j` commandline option.
With `-j 1`, you can disable the parallelization entirely and will also reduce the output slightly.

To use as much threads as your CPU has cores, you can use `-j 0` (which is also the default) to instruct SBuild to auto-detect the used thread pool size.   

[NOTE]
====
To make a custom jobs setting permanent, you can add it to the `${HOME}/.sbuildrc` file.

[source,conf]
.`${HOME}/.sbuildrc`
----
jobs=4
----
====


== Failing the Build

When SBuild detects an execution failure in a target, it will interrupt all other parallel executing targets, print a error message with some details about the initially failed target and quit.

// TODO: example

Sometimes, it is desirable to fail the build as late as possible and not stop at the moment the first target fails. 
Of course, the build can not be completed successfully, but some targets may complete.
In such scenarios, you can use the `--keep-going` or `-k` commandline option. 
When specified, SBuild tries to complete as much targets as possible before failing with a descriptive error message indicating which targets failed and which could not be completed because of unsatisfied dependencies.

== Repetitive tasks

// TODO  