language: java

sudo: false

env: 
  global:
  - LC_ALL: C
  - GH_REF: github.com/SBuild-org/SBuild-org.github.io
  - secure: "RnGwPUYOrqX4ue/U+VKVSaeXDfSOPSK2L2Vp1/InuO2SdkD1SispZx2oLIJAxgPMCMOMQVYG8SZPJaDKOEhTM8Z30k7GcJ57W8ZaXLnd6JGXnNlCeq0lnvnWhcoR75QCYQowu8Q5PJlvCRjVNRjnrV7F6G3S+S3aFFq+l6ld+Qs="

script: "./build-and-deploy-to-github.sh"

