= Download
Tobias Roeser
2014-04-04
:jbake-type: page
:jbake-status: published


== Stable Releases

:sbuildversion: 0.7.7

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.5

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.4

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.3

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.2

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.1

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]


== Development Milestones

:sbuildversion: 0.7.9013

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

:sbuildversion: 0.7.9010.0-8-0-M1

* SBuild {sbuildversion} Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
