= Download
Tobias Roeser
2014-04-04
:jbake-type: page
:jbake-status: published


:sbuildversion: 0.7.9010.0-8-0-M1

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]


:sbuildversion: 0.7.5

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]


:sbuildversion: 0.7.4

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

// TODO: single jars

:sbuildversion: 0.7.3

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]

// TODO: single jars


:sbuildversion: 0.7.2

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]



:sbuildversion: 0.7.1

== SBuild {sbuildversion}

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* http://sbuild.tototec.de/sbuild/projects/sbuild/files[Other downloads...]


== Older Releases

Please download older releases from http://sbuild.tototec.de/sbuild/projects/sbuild/files[sbuild.tototec.de].
