= Documentation
Tobias Roeser
2014-04-04
:jbake-type: page
:jbake-status: published
:sbuildversion: 0.7.6

== SBuild {sbuildversion} - Current stable Release

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]

* Scaladoc
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]

== Older Releases

:sbuildversion: 0.7.5

== SBuild {sbuildversion} - Current stable Release

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]

* Scaladoc
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]


:sbuildversion: 0.7.4

== SBuild {sbuildversion} - Current stable Release

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]

* Scaladoc
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]


:sbuildversion: 0.7.3

== SBuild {sbuildversion} - Current stable Release

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]

* Scaladoc
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]

:sbuildversion: 0.7.2

=== SBuild {sbuildversion}

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]

* Scaladoc
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]

:sbuildversion: 0.7.1

=== SBuild {sbuildversion}

* link:{path_doc_sbuild}/{sbuildversion}/index.html[SBuild Reference Manual {sbuildversion}]
* link:/news/2013/12/20/The-Plugin-System-of-SBuild-0.7.1.html[The Plugin System of SBuild 0.7.1]
* http://sbuild.tototec.de/sbuild/projects/sbuild/wiki/Documentation[The old Documentation]

* Scaladoc
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference]
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference]
** http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference]


=== SBuild 0.7.0

* link:/news/2013/12/06/The-Plugin-System-of-SBuild-0.7.0.html[The Plugin System of SBuild 0.7.0]

=== Before SBuild 0.7.0

Information and documentation about previous versions can be found on the http://sbuild.tototec.de/sbuild/projects/sbuild/wiki[SBuild Redmine] page.

== Release History

* link:/releases[All Release Notes]

== FAQ

Read our link:/faq/index.html[Frequently asked Questions].