= Community
Tobias Roeser
2013-12-13
:jbake-type: page
:jbake-status: published

You want to get part of SBuild development? You want to report a Bug or an idea? 

*Welcome! We are happy to have you aboard.*

You can use the following resources to collaborate and contribute:

*Mailing list* 

* https://groups.google.com/forum/#!forum/sbuild-dev[sbuild-dev] - Discussions about the development of SBuild
* https://groups.google.com/forum/#!forum/sbuild-user[sbuild-user] - Forums for SBuild users

*Bug tracker*

* https://sbuild.tototec.de/sbuild/projects/sbuild/issues[Redmine] - We used the Redmine ticket system, but plan to migrate to Github. Until the migration is finished, you can only create tickets here. 
* _In Progress: Github_ - After the migration is finished, we will accept isses and pull requests via Github. Until the migration to Github is finished, we disabled the Github issue tracker for public use.

Previously, we also had https://sbuild.tototec.de/sbuild/projects/sbuild/boards[*Forums*], but we plan to shut them down. Please use one of the other community channels, especially the mailing lists. 
