= SBuild 0.7.3
Tobias Roeser
2014-03-18
:jbake-type: page
:jbake-status: published
:previoussbuildversion: 0.7.3
:sbuildversion: 0.7.4

Release date: 2014-03-20

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:/download[Other downloads...]


== Online Documentation

* link:/doc/sbuild/{sbuildversion}[SBuild Documentation]
* link:/news/2014/03/20/SBuild-0.7.4-released.html[Announcement]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference (Scaladoc)]


[#Changelog]
== Changelog

Changes since link:SBuild-{previoussbuildversion}.html[SBuild {previoussbuildversion}]

.SBuild Runner
* Re-enabled parallel loading of classes in project class loader which should
  finally fix the deadlock issue introduced with 0.7.2. With this fix, SBuild
  requires Java 7 to build, but at runtime Java 6 should be sufficient.

All Releases: link:index.html[Release History]
