= SBuild 0.1.3
Tobias Roeser
2012-10-18
:jbake-type: page
:jbake-status: published
:sbuildversion: 0.1.3
:previoussbuildversion: 0.1.2

Release date: 2012-10-18

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:/download[Other downloads...]

== Upgrade from SBuild 0.1.2

If you have written you own SchemeHandler, you have to adapt it to the new SchemeHandler API. The method resolve got a second parameter targetContext of type TargetContext.



[#Changelog]
== Changelog

Changes since link:SBuild-{previoussbuildversion}.html[SBuild {previoussbuildversion}]

* Improved classloading for ScalaTest and JUnit addons.
* Incompatible API change: SchemeHandler can now have dependencies, when implementing the trait SchemeHandlerWithDependencies and have access to them through the TargetContext, which will be given as parameter into resolve method.
* Added new ZipSchemeHandler to reference zipped resources, a typical use case for original online dependencies like TestNG, JUnit or SWT.
* Fixed a bug, where the self-evaluated up-to-date state of phony targets was lost causing some unnecessary executions.


All Releases: link:index.html[Release History]
