= SBuild 0.7.5
Tobias Roeser
2014-04-04
:jbake-type: page
:jbake-status: published
:previoussbuildversion: 0.7.4
:sbuildversion: 0.7.5

Release date: 2014-04-04

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:/download[Other downloads...]


== Online Documentation

* link:/doc/sbuild/{sbuildversion}[SBuild Documentation]
* link:/news/2014/04/04/SBuild-0.7.5-released.html[Announcement]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference (Scaladoc)]


[#Changelog]
== Changelog

Changes since link:SBuild-{previoussbuildversion}.html[SBuild {previoussbuildversion}]

.SBuild Runner
* Disabled parallel classloading in plugin classloader. This effectivly speeds
  up initialization time and avoids some not that well understood linkage
  errors.

All Releases: link:index.html[Release History]
