= SBuild 0.7.3
Tobias Roeser
2014-03-18
:jbake-type: page
:jbake-status: published
:previoussbuildversion: 0.7.2
:sbuildversion: 0.7.3

Release date: 2014-03-18

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:/download[Other downloads...]


== Online Documentation

* link:/doc/sbuild/{sbuildversion}[SBuild Documentation]
* link:/news/2014/03/18/SBuild-0.7.3-released.html[Announcement]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference (Scaladoc)]
* {url_uploads_sbuild}/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference (Scaladoc)]


[#Changelog]
== Changelog

Changes since link:SBuild-{previoussbuildversion}.html[SBuild {previoussbuildversion}]

.SBuild Runner
* Fixed a sporadically deadlock when running parallel jobs, introduced in 0.7.2.
* Fixed output of names for phony targets.
* Output of `--help` now uses the full terminal width but falls back to 80 columns if the width can not be evaluated.


All Releases: link:index.html[Release History]
