= SBuild 0.3.1
Tobias Roeser
2013-01-17
:jbake-type: page
:jbake-status: published
:sbuildversion: 0.3.1
:previoussbuildversion: 0.3.0

Release date: 2013-01-17

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:/download[Other downloads...]


[#Changelog]
== Changelog

Changes since link:SBuild-{previoussbuildversion}.html[SBuild {previoussbuildversion}]


* Added ability to translate/resolve (any) target ref(s) to files.
* Changed default to not use fsc when compiling build files and added new commandline option "--fsc" to enable fsc.
* Pathes and file dependencies pointing to symbolic links will be no longer implicitly resolved.
* ZipSchemeHandler: Fixed up-to-date detected issue, when a ZIP entry gets always reextracted.
* ZipSchemeHandler: Fixed bug, where extraction of files, that don't exists in ZIP file, were silently ignored.
* New BndJar Addon to generate OSGi Bundles based on bndlib.
* Fixed Windows start script.

All Releases: link:index.html[Release History]
