= SBuild 0.7.0
Tobias Roeser
2013-12-06
:jbake-type: page
:jbake-status: published

Release date: 2013-12-06

== Download

* SBuild Distribution: {url_uploads_sbuild}/{sbuildversion}/sbuild-{sbuildversion}-dist.zip[sbuild-{sbuildversion}-dist.zip]
* link:download[Other downloads...]


== Online Documentation

* Documentation process is currently in progress...
* link:/news/2013/12/06/The-Plugin-System-of-SBuild-0.7.0.html[The new Plugin System of SBuild 0.7.0]
* http://sbuild.tototec.de/sbuild/projects/sbuild/wiki/Documentation[SBuild Documentation]
* http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild/#de.tototec.sbuild.package[SBuild Public API Reference (Scaladoc)]
* http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.addons/#de.tototec.sbuild.addons.package[SBuild Addons API Reference (Scaladoc)]
* http://sbuild.tototec.de/static/doc/sbuild/{sbuildversion}/scaladoc/de.tototec.sbuild.ant/#de.tototec.sbuild.ant.package[SBuild Ant Support and Wrapper Reference (Scaladoc)]

[#Changelog]
== Changelog

Changes since link:SBuild-0.6.0.html[SBuild 0.6.0]

.SBuild core and SBuild Runner
* Plugin system with isolated plugin class loading and hierarchical dependency resolving.
* @classpath annotation not handles all entries as plugins (the JAR manifest will be scanned for SBuild header entries). This can be disabled by adding the prefix "raw:" to the entry.
* Extended Project API to support Plugins, mostly for internal use.
* Added Plugin trait/object to SBuild API to activate and interact with plugins.
* Project resources (@classpath, @include) will be resolved in parallel.
* Added Logger API.
* Replaced internal SBuildLogger by SBuildMonitor API.
* Support for localized output and a partial German translation.
* Check and warn for identical module definitions in a project.
* ZipSchemeHandler: When an to-be-extracted resource already exists, but has an older modification date than the zip file, re-extract it and set the modification date accordingly.
* The cmdline shortcuts support is now able to also match hyphen-delimited target names, e.g. "uS" would match "update-site".
* The project runtime classpath does include the scala library only once.
* New RichFile API with contains so filerealted methdod and can be used in implicit conversion.
* Some API cleanups.
* New --keep-going commandline option to continue to build unaffected targets even if some targets failed. At the end, a summary of all failed and skipped targets is shown. This might be useful e.g. to run all test targets (in a CI server) which otherwise might fail the build to early.
* Lock mechanism to avoid compilation of buildfiles concurrently.
* Various cleanups and package reorganizations.
* Started documentatio in AsciiDoc format.
* Added --list-plugins and --list-available-plugin commandline options to show used and unused but available plugins.

.SBuild Addons
* New TestNG addon.
* ScalaTest: Allow configuration of more than one reporter. Added new parameters: graphicalOutputSettings, standardOutputSettings, standardErrorSettings, outputFile, utputFileSettings, xmlOutputDir, reporterClass, additionalScalaTestArgs. Deprecated parameter: reporter.
* ForkSupport: Added new parameters "failOnError" and "env" to ForkSupport.runAndWait.


All Releases: link:index.html[Release History]